name: LAST

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  LAST-Security-Scan:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all history for all branches and tags
        ref: ${{ github.head_ref }}
    
    - name: Fetch target branch
      run: git fetch origin ${{ github.base_ref }}:${{ github.base_ref }}

    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install latio
    
    - name: Analyzing the code with LAST
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        latio partial-github . ${{ github.base_ref }} ${{ github.head_ref }}

