name: LAST

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  LAST-Scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: actions/checkout@v4
      with:
        repository: latiotech/LAST
        path: LAST
        ref: main

    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r LAST/requirements.txt
    
    - name: where
      run: pwd
    
    - name: Analyzing the code with LAST
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: python LAST/LAST.py partial .

